services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis


  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  # rqworker:
  #   build: .
  #   command: rq worker --url redis://backend-redis-1:6379/0
  #   depends_on:
  #     - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend